### ISSUE TITLE
PoS and TX Messages support needed

### ISSUE THREAD

**Issue by himikk** [simplecrypto/cryptokit#9]
Do you have any plans to realize PoS and TX Messages support?
I see you try to add TX Messages in 'tx_msg' branch.

**Comment by icook** [comment]
This has been completed for someone as commissioned closed source, but will be released in a few months here.

**Comment by himikk** [comment]
Can you contact me? I send a message to your email.

**Comment by icook** [comment]
Replied.

**Comment by sigwo** [comment]
Was this ever fully implemented into powerpool and correspondingly into simplecoin_multi?
